Fix uncaught TypeError
PHP-CS-Fixer/PHP-CS-Fixer pull request #6719
Opened 2022-12-20 08:50 UTC by jschaedl

fixes #6718

2022-12-23 16:47 UTC, julienfalque reviewed
Thank you for tackling this!

2022-12-23 16:47 UTC, julienfalque commented on src/Console/Command/FixCommand.php
> +            $finder = new \ArrayIterator($finder);
Can we move this line before this `if`? This would remove the need to do the same at line 316.

2022-12-23 17:00 UTC, julienfalque commented on src/Console/Command/FixCommand.php
> +            $finder = new \ArrayIterator($finder);
Actually it might be better to replace `count()` with `iterator_count()` so we don't need to rely on `ArrayIterator`.

2022-12-23 20:21 UTC, kubawerlos requested changes
Let's have a test to prevent regression.

2023-01-02 23:11 UTC, keradus commented
thanks everyone involved here, especially @jschaedl !
I will let myself to close this PR and merge #6734 instead, as it also has a test included!

2023-01-02 23:11 UTC, closed without merging