[PHP8.2] Support for readonly classes
PHP-CS-Fixer/PHP-CS-Fixer pull request #6745
Opened 2023-01-09 15:58 UTC by Wirone

These are changes initially proposed by SpacePossum in #6624 but abandoned due to personal reasons. Since it's accepted by the author to use these changes, I've just applied the full patch, so we can continue work.

2023-01-09 16:04 UTC, Wirone commented
@keradus this is only patch applied from @SpacePossum's commit [taken from here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/fb4a4298334be5cbf54bf80c1fbd224c9eee903f.patch), no new changes. I wanted to check if it passes on newest `master` and provide changes if required. At this point it is 1:1 with #6624 🙂

2023-01-21 08:09 UTC, kubawerlos requested changes

2023-01-21 08:09 UTC, kubawerlos commented on tests/Tokenizer/TokensAnalyzerTest.php
> +     * @param array<string, int> $expectedModifiers
```suggestion
     * @param array<string, null|int> $expectedModifiers
```

2023-01-21 08:09 UTC, kubawerlos commented on tests/Tokenizer/TokensAnalyzerTest.php
> +     * @param array<string, int> $expectedModifiers
```suggestion
     * @param array<string, null|int> $expectedModifiers
```

2023-01-21 08:09 UTC, kubawerlos commented on tests/Fixer/ClassNotation/FinalInternalClassFixerTest.php
> +            null,
```suggestion
            '<?php readonly class A{}',
```

2023-02-27 10:45 UTC, Wirone commented
FYI: Sorry for lack of response, I did not have time lately, but I'll try to look at it later today 🙂

2023-02-27 12:53 UTC, Wirone commented on tests/Tokenizer/TokensAnalyzerTest.php
> +    public function provideGetClassyModifiersOnPhp82Cases(): iterable
Sure, added some more test cases 👍

2023-02-27 20:54 UTC, kubawerlos approved these changes

2023-02-28 21:52 UTC, keradus commented
big thanks @SpacePossum and @Wirone , as well as @kubawerlos for nice review!

2023-02-28 21:53 UTC, merged

2023-02-28 22:41 UTC, SpacePossum commented
nice one @Wirone :+1:  :tada:

2023-03-01 07:14 UTC, Wirone commented
To be fair, it's all thanks to @SpacePossum - I only did maintenance work to refresh the branch and fix little issues to align the code with current CS rules. Anyway, happy that `readonly` classes support got merged 🎉