bug: AbstractPhpUnitFixer - support attribute detection in docblock insertion
PHP-CS-Fixer/PHP-CS-Fixer pull request #6858
Opened 2023-03-25 03:19 UTC by paulbalandan

Partial fix of #6795

2023-03-25 12:29 UTC, Wirone requested changes
Nice work! 🍻 But I believe we need more complex cases too.

2023-03-25 12:29 UTC, Wirone commented on tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
Can we add cases where multiple attributes are above the class, please? Here, and other tests related to atteibutes.

2023-03-26 14:09 UTC, kubawerlos commented
Isn't this a feature, not a bug(fix)?

2023-03-26 15:03 UTC, paulbalandan commented
> Isn't this a feature, not a bug(fix)?

Not really sure. Since this was reported as a bug, I noted the PR as a bugfix.

2023-03-26 15:05 UTC, kubawerlos commented
> Since this was reported as a bug

What do you mean? Linked issue is a feature request.

2023-03-26 16:36 UTC, paulbalandan commented
> > Since this was reported as a bug
> 
> What do you mean? Linked issue is a feature request.

My understanding is it is a bug since the docblock is inserted incorrectly. But you're correct, it is indeed a feature request.

2023-03-26 16:38 UTC, paulbalandan commented on tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
Sure. But for more complex cases I'm not sure what to add. 😂

2023-03-26 16:44 UTC, Wirone commented on tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
Just what I wrote, multiple attributes 🙂. I believe your current implementation don't support cases like this:

```
<?php

#[SimpleTest]
#[AnotherAttribute]
class Test extends TestCase
{
}
```

2023-03-26 17:30 UTC, paulbalandan commented on tests/Fixer/PhpUnit/PhpUnitInternalClassFixerTest.php
I believe it is now covered by https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6858/commits/17302b3acbdfce4d7e522f15e2f6fbfe4c6789be

2023-03-26 19:14 UTC, kubawerlos approved these changes

2023-03-28 09:56 UTC, Wirone approved these changes

2023-03-31 21:36 UTC, merged

2023-03-31 21:36 UTC, kubawerlos commented
thank you @paulbalandan