bug: VoidReturnFixer - fix for intervening attributes
PHP-CS-Fixer/PHP-CS-Fixer pull request #6863
Opened 2023-03-26 17:38 UTC by paulbalandan

Fixes #6690

2023-03-26 19:55 UTC, kubawerlos approved these changes

2023-03-27 17:10 UTC, Wirone requested changes
I believe it would be good if there was a integration test that would ensure that `@return void` is removed when `no_superfluous_phpdoc_tags` fixer is enabled 🤔. WDYT @kubawerlos?

2023-03-28 23:14 UTC, mvorisek commented on src/Fixer/FunctionNotation/VoidReturnFixer.php
> +        static $previousTokens = [
is `static` really faster/needed?

2023-03-29 08:18 UTC, paulbalandan commented on src/Fixer/FunctionNotation/VoidReturnFixer.php
> +        static $previousTokens = [
Thanks!

2023-04-20 22:48 UTC, Wirone approved these changes

2023-04-20 22:49 UTC, merged

2023-04-20 22:49 UTC, Wirone commented
Thank you, @paulbalandan 🍻