bug: make `php_unit_namespaced` less greedy
PHP-CS-Fixer/PHP-CS-Fixer pull request #6952
Opened 2023-05-13 00:45 UTC by Wirone

Fixes #6413.

2023-05-13 07:49 UTC, kubawerlos requested changes
Two more test cases please:
```php
    'class_mapping_bogus_fqcn_lowercase' => [
        '<?php new \phpunit\framework\mockobject\stub\returnstub();',
        '<?php new \phpunit_framework_mockobject_stub_return();',
    ],
    'class_mapping_bogus_fqcn_upercase' => [
        '<?php new \PHPUNIT\FRAMEWORK\MOCKOBJECT\STUB\RETURNSTUB();',
        '<?php new \PHPUNIT_FRAMEWORK_MOCKOBJECT_STUB_RETURN();',
    ],
```
(best would right below case "class_mapping_bogus_fqcn")

2023-06-02 15:31 UTC, SpacePossum commented
Looking through PHPUnit v4, 5, 6 and 7 there never were `PHPUnit_` constants (in any casing).
The tests of the rule also imply that constants should not be touched.
Fixing `require PHPUNIT_COMPOSER_INSTALL` is a bug, as it is a use of a constant, not a class reference.

As such, I think the solution direction should be having the rule check the `T_STRING` token  against `ClassyAnalyzer::isClassyInvocation` , which should filter out all the `consts` usage.

2023-06-06 01:31 UTC, Wirone commented
Thanks @SpacePossum for the tip! I had to handle imports too, but `ClassyAnalyzer` did half of a job 😁.

2023-06-08 11:55 UTC, kubawerlos approved these changes

2023-06-08 12:05 UTC, merged