bug: Fix return_assignment not formatting when variables are used in finally
PHP-CS-Fixer/PHP-CS-Fixer pull request #6960
Opened 2023-05-15 02:35 UTC by Yurunsoft

fix #6691

2023-05-15 16:15 UTC, kubawerlos requested changes
Please add a test case with an input code like this:
```php
<?php
function foo()
{
    if (isSomeContiotion()) {
        $result = getSomeResult();
        return $result;
    }

    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    } finally {
        baz($result);
    }
}
```

2023-05-16 17:29 UTC, kubawerlos requested changes
One more test case please, this time with input:
```php
<?php
function foo()
{
    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    }

    if (isSomeContiotion()) {
        $result = getSomeResult();
        return $result;
    }

    try {
        $result = $a + $b;
        return $result;
    } catch (\Throwable $th) {
        throw $th;
    } finally {
        echo "result:", $result, \PHP_EOL;
    }
}
```

2023-05-16 17:29 UTC, kubawerlos commented on src/Fixer/ReturnNotation/ReturnAssignmentFixer.php
> +            if (null !== $tryIndex && $tryIndex > $functionOpenIndex && $tryIndex < $functionCloseIndex) {
Can we have this extracted to a separate method to have it easier to comprehend in the future?

2023-05-19 15:17 UTC, kubawerlos submitted a review, later dismissed
No more tricky cases from me, only small changes, and will be good.

2023-05-19 15:17 UTC, kubawerlos commented on src/Fixer/ReturnNotation/ReturnAssignmentFixer.php
> +        if (null === $tryIndex || $tryIndex <= $functionOpenIndex || $tryIndex >= $functionCloseIndex) {
```suggestion
        if (null === $tryIndex || $tryIndex <= $functionOpenIndex) {
```
The last condition is not possible, right? `$tryIndex` is smaller than `$functionCloseIndex` when we enter the `isUsedInCatchOrFinally` function and with `getPrevTokenOfKind` value of `$tryIndex` can be only smaller.

2023-05-19 15:17 UTC, kubawerlos commented on tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php
> +                    if (isSomeContiotion()) {
I know that this "typo" is from my suggestion, but you might want to fix it as it will be your name in `git blame` for it 😛

2023-05-20 00:53 UTC, Yurunsoft commented
@kubawerlos Thank you very much, I have solved all these problems.

2023-05-20 07:30 UTC, Wirone requested changes
I believe we need test case with multiple `catch` blocks, something like:

```php
function foo() {
    try {
        $bar = bar();

        return $bar;
    } catch (\LogicException $e) {
        echo "catch ... ";
    } catch (\RuntimeException $e) {
        echo $bar;
    }
}
```

(Writing code on mobile 😩😅)

2023-05-25 03:07 UTC, Yurunsoft commented
> I believe we need test case with multiple `catch` blocks, something like:
> 
> ```
> function foo() {
>     try {
>         $bar = bar();
> 
>         return $bar;
>     } catch (\LogicException $e) {
>         echo "catch ... ";
>     } catch (\RuntimeException $e) {
>         echo $bar;
>     }
> }
> ```
> 
> (Writing code on mobile 😩😅)

Thanks, it has been fixed.

2023-05-25 06:22 UTC, Wirone commented on tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php
> +            'try finally2' => [
```suggestion
            'try with multiple catch blocks' => [
```

There's no `finally` here 😉. And cases should be described in a way that intention is clear.

2023-05-25 09:08 UTC, Wirone commented
@Yurunsoft to speed up things I've rebased your branch and added [more test cases](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6960/commits/2b5f12437b9244be51b6a6594b5b5ca7572ff15d), please update your local branch to current remote revision.

2023-05-25 13:20 UTC, Wirone commented
@kubawerlos @Yurunsoft FYI: I looked into current tests and [there is case for `$$`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/08ec0679e5c61c2a7d2be3c0ca5c63c5c5c4ba3e/tests/Fixer/ReturnNotation/ReturnAssignmentFixerTest.php#L907-L916) which IMHO does not make sense 😅. It could be changed to `return $$c;` and would work the same, so technically this is wrong test case. But the good part is that case like below also works properly too (is not changed):

```php
<?php
function foo()
{
    try {
        $result = getResult();
        return $result;
    } catch (\Throwable $exception) {
        error_log($exception->getMessage());
    } finally {
        $foo = 'result';
        baz($$foo);
    }
}
```

Do we want to change the test case for `$$` here, to reflect that scenario better?

2023-06-06 09:22 UTC, Wirone approved these changes

2023-06-06 09:30 UTC, merged

2023-06-06 09:31 UTC, Wirone commented
Thank you @Yurunsoft 🍻