fix: consider function modifiers for `statement_indentation`
PHP-CS-Fixer/PHP-CS-Fixer pull request #6978
Opened 2023-05-20 07:43 UTC by msbit

If a function is prefixed by a visibilty modifier or `static`, in most scenarios it won't be considered the start of a `block_signature` scope.

This generalises the detection of the start of a block signature to be a sequence of token kinds, and adds sequences for:

    (private|protected|public) function
    (private|protected|public) static function
    static function

2023-05-20 07:45 UTC, msbit commented
This should sort out https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6699 but I'm aware there is likely a better/less brittle way of doing it.

Anyhow, this should get the ball rolling, any input more than welcome ✌️

2023-05-20 14:15 UTC, Wirone requested changes
Hi @msbit, thank you for your contribution 🙂. I really like the fix, but I believe it isn't the best implementation for that. First of all, there are more method modifiers than those you covered: `final` and `abstract`. Second: instead of explicitly defining all possible sequences, maybe it would be better to rewind index to first available modifier, like `NoPhp4ConstructorFixer::findFunction()` does? 🤔 

The best thing to do would be extracting such logic to one of analyzers, so it could be reused between fixers.

What do you think @kubawerlos, @keradus?

2023-05-21 06:37 UTC, msbit commented
Thanks @Wirone! Yes, pretty obvious oversight eh? 🤣

Using an extracted `findFunction` sounds lightyears better; I've had a play around with it, and it's easy enough to setup the appropriate scope `end_index`. The curly bit is that by the time `T_FUNCTION` is encountered (as a cue to attempt `findFunction`), the common `$lastIndent` variable has been adjusted to a value that doesn't match what it should be before the modifiers. My previous stab at this serendipitously avoided this by matching on the first modifier token, when the `$lastIndent` value is correct.

I've had a look through the whitespace case towards the end of the loop (where `$lastIndent` is managed), but the logic is too opaque for me to work through; I'd appreciate any guidance on how to get the appropriate value at the time of adding the scope.

2023-05-27 03:54 UTC, msbit commented
@Wirone all good.

I've had another go at it, with my thinking being:

* track the current `lastIndent` value whenever we encounter a modifier
* unwind this list of indents for each modifier when we encounter `T_FUNCTION` and use the first one when creating the scope

Interestingly, as I'd misspelled `modifierIndents` with my original commit yesterday (thanks `phpstan` :D), the second part was not acting any differently to before, which suggests that just consuming the modifiers (ie not allowing `lastIndent` to be changed later on) is sufficient.

I've fixed up my misspelling and re-committed, so the full idea is there, and I'm spending a bit of time debugging through the `content`/`lastIndent` updating code later on in the loop.

Also, I'd taken a look at using `findFunction` (as you'd suggested) but it's behaviour for `abstract` functions  (ie without body) seemed to mess up the created scope so I walk backwards in a local loop instead.

2023-05-27 06:32 UTC, Wirone commented on tests/Fixer/Whitespace/StatementIndentationFixerTest.php
Can we have also test cases with multiple modifiers, like `final public static function`?

2023-05-29 08:29 UTC, msbit commented on tests/Fixer/Whitespace/StatementIndentationFixerTest.php
I've added an (exhaustive?) permutation of modifiers to the test ✌️

2023-06-12 21:00 UTC, Wirone approved these changes

2023-06-13 09:44 UTC, Wirone commented
I have offline confirmation from @kubawerlos, so let's merge 👍.

2023-06-13 09:44 UTC, merged

2023-06-13 10:10 UTC, Wirone commented
Thanks @msbit and welcome in the contributors group 🍻🤩.

2023-06-13 10:58 UTC, msbit commented
Thanks @Wirone! Happy to contribute.