bug(YieldFromArrayToYieldsFixer): skip touching empty array
PHP-CS-Fixer/PHP-CS-Fixer pull request #7273
Opened 2023-09-06 20:46 UTC by keradus

closes #7270

2023-09-06 20:47 UTC, keradus commented
cc @enumag  , fyi @kubawerlos

2023-09-06 21:18 UTC, keradus commented
fair question, let's add a test for it too

2023-09-07 08:40 UTC, Wirone requested changes

2023-09-07 08:40 UTC, Wirone commented on tests/Fixer/ArrayNotation/YieldFromArrayToYieldsFixerTest.php
> +        yield 'from empty arrays' => [
I believe data set's name should represent the intent of the test case.

```suggestion
        yield 'skip empty arrays' => [
```

2023-09-07 08:40 UTC, Wirone commented on tests/Fixer/ArrayNotation/YieldFromArrayToYieldsFixerTest.php
Maybe it's an overkill, but what about:

```php
function foo1()
{
    yield from [
        // Inline comment,
        # and another one
    ];
}
```

- all comment styles covered
- multiline covered
- `,` is important in terms of this fixer (looking for items in the array), so maybe it's good to ensure that it's not matched within comment (even though it's rather impossible in terms of tokenizing 😝).

2023-09-07 10:22 UTC, keradus commented on tests/Fixer/ArrayNotation/YieldFromArrayToYieldsFixerTest.php
if you consider this test missing to be a blocker for PR, happy to add it

yeah, not sure about `,` in context of tokenizer, but won't hurt so I'm ok to add it

2023-09-07 11:03 UTC, Wirone approved these changes

2023-09-07 11:13 UTC, merged