fix: NoSpacesAfterFunctionNameFixer should not fix parentheses that are not part of a language construct
PHP-CS-Fixer/PHP-CS-Fixer pull request #7521
Opened 2023-12-08 00:33 UTC by kamil-tekiela

Ref. #7516

This removes the "feature" that removed spaces between certain language constructs and unrelated parentheses that followed after it. The fixer still removes spaces between language constructs that use parentheses as part of their syntax, e.g. `empty()` or `isset()`.

2023-12-08 06:37 UTC, kubawerlos requested changes
> certain language constructs

why those 6 language constructs? E.g. `exit` is also a language construct that can be used without parentheses.

Moreover, what if some people prefer to have consistency with spaces before parentheses that are expression calls over distinguishing what is a language construct and what is not? Wouldn't making this configurable be better?

2023-12-08 13:10 UTC, kamil-tekiela commented
> > certain language constructs
> 
> why those 6 language constructs? E.g. `exit` is also a language construct that can be used without parentheses.
> 
> Moreover, what if some people prefer to have consistency with spaces before parentheses that are expression calls over distinguishing what is a language construct and what is not? Wouldn't making this configurable be better?

As far as I know, `exit` and `die` have only two variants. `exit;` and `exit(<status>);`. Since there is no way to follow `exit` with unrelated parameters, it can be treated as "function-y language construct".

2023-12-08 13:20 UTC, kamil-tekiela commented
> @kamil-tekiela I propose boolean config option `treat_language_constructs_as_functions` or `enable_function_like_language_constructs` with default value `true` to keep current behaviour. Then, instead of removing the logic you should trigger it only if enabled. The description of the option should include information that it applies only if language construct is used as function-like call (`echo('foo')`) and does not apply for expressions (`echo ($foo ? 'bar' : 'baz') . 'buzz';`).

There is no such thing as `function-like call (`echo('foo')`)`. It's just `echo` with its operand inside useless parentheses. 

Furthermore, why should we special case this? `echo (foo);` and `echo ('f'.'o').'o';` is the same concept. 

>`treat_language_constructs_as_functions` or `enable_function_like_language_constructs`

I am strongly opposed to it because that would make things even more confusing. We already treat language constructs as functions in this fixer. The language constructs that look like functions are covered by this logic. I only fixed it so that the fixer doesn't apply to language constructs that NEVER look like a function. Introducing a boolean flag like this would be confusing. We would be back to the start and this whole PR would be a waste of time. The whole point is to fix the current logic so that it correctly applies this fixer to function-like constructs but not to language constructs without parentheses.

2023-12-08 14:11 UTC, Wirone commented
> There is no such thing as "function-like call (`echo('foo')`)". It's just `echo` with its operand inside useless parentheses. 

At the same time you mention "function-y language construct" 🤷‍♂️. It is exactly the same concept, named differently, and expanded to all constructs with single `()`.

> Furthermore, why should we special case this? `echo (foo);` and `echo ('f'.'o').'o';` is the same concept. 

Theoretically yes, but as already mentioned all of them can look "function-y", and people may have different preference than you when it comes to it.

> I only fixed it so that the fixer doesn't apply to language constructs that NEVER look like a function

I don't even consider it as a bug, it was proper feature that you removed. It is backward-incompatible with what people currently use in their apps. Please look [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst).

> Introducing a boolean flag like this would be confusing. We would be back to the start and this whole PR would be a waste of time. The whole point is to fix the current logic so that it correctly applies this fixer to function-like constructs but not to language constructs without parentheses.

Yes, current state of the PR would be lost and your work wasted, but please look [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/CONTRIBUTING.md#how-to-contribute), especially this:

> if you work on existing fixers then don't change existing test cases, because these are contract between the maintainers and users (they ensure how tool works).

The guideline was ignored and here we are 😉. I understand you want this particular fixer to behave differently, but let's introduce config flag for it so we can continue with current behaviour and allow people to change it as an opt-in.

2023-12-08 15:41 UTC, kubawerlos commented
> It encourages bad coding practices that can lead to bugs

It has been here for a long time and you are the first person to make such a claim - do you consider the scenario that you are wrong about that, or is it that everyone else is wrong and you are the only one who is right?

> Then this means that there is no way to fix wrong behaviour of any of the fixers

Apparently, you did not understand it correctly, of course bugs could be - and are - fixed, take a look [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7522).

> But my point was that adding the flag is pointless. It wouldn't change anything

It would change exactly what you are trying to do in this PR, but not as breaking compatibility change, but as configured option of choice for every user.

2023-12-08 15:50 UTC, kamil-tekiela commented
> It has been here for a long time and you are the first person to make such a claim - do you consider the scenario that you are wrong about that, or is it that everyone else is wrong and you are the only one who is right?

I don't make new claims. I simply stated a fact and pointed to what is written in PHP manual. I didn't write that part in the manual but I agree with it. 

The thing with bugs is that until someone finds it and raises an issue, it remains part of the software. There has to be the first person to raise the issue. 

There's no need to attack me personally. Just focus on the topic. All I am trying to do in this PR is to fix a bug. If the attitude of maintainers is that bugs that have been part of the released product must remain there, so be it.

2023-12-08 16:00 UTC, Wirone commented
> If the attitude of maintainers is that bugs that have been part of the released product must remain there, so be it.

Well, that's rude. You consider it as a bug, we don't. You want to "break" everyone's codebases with a change in a widely used ruleset, we don't. Just focus on the topic and decide if you're interested in providing a configuration option to keep current behaviour as default, with an ability to switch to your approach - if not, I believe we can close this PR as it's rather not going to be merged in the current state.

2023-12-08 16:17 UTC, kamil-tekiela commented
> This repo is not about "I like it that way and it must be that way", but about promoting good practices that the majority agree with.

And I completely agree with this. That's the whole reason why I want to fix this. There is already a fixer to remove the unnecessary parentheses `no_unneeded_control_parentheses`. It's promoting good practices.

> You want to "break" everyone's codebases with a change in a widely used ruleset, we don't.

No, I don't want to break anyone's codebase. The change I propose doesn't break anything. I'd imagine it's pretty rare that users intentionally add parentheses after `echo` or `include` and want to make it look like a function. 

I'm sorry that you don't see it as a bug. Evidently, I can't convince you to see that the fixer doesn't do what it was designed to do. I found a bug when using PHP-CS-fixer, I reported it, and I submitted a PR to fix it. I don't fully understand why you don't think it's a bug, but it is your prerogative. You are the maintainers of this project. There's nothing rude about me acknowledging this. 

I am not interested in adding a configuration option for two reasons:
1. I don't know what this configuration option would do. It was not my idea to add one. 
2. I believe it would be a step in the wrong direction. It would make it seem as the project endorses adding parentheses in weird places, despite there existing a dedicated fixer to removing them. 

As an alternative, you may want to consider expanding this fixer to cover other things. Add missing constructs and not only `echo` and `include`. PHP has more [keywords](https://www.php.net/manual/en/reserved.keywords.php) that can be followed by optional parentheses. But then the name and the description of this fixer should make it clear that it's not about just functions/methods. 

I am sorry if I have offended anyone. I only wanted to fix an issue I reported.

2023-12-08 16:43 UTC, kamil-tekiela commented
> so I believe the majority of people may have "function-like language constructs" in their code, and this PR would force them to change the way how these are formatted.

I don't understand this. As far as I am aware my PR wouldn't do that. Maybe I missed something. I executed the tests and it still removed spaces in "function-like language constructs". This hasn't changed. 

> There's no need to be grumpy and suggest including other language constructs in this fixer.

I also don't understand this. I only suggested that this fixer's stated purpose should be clarified and adjusted to match either way. What's wrong with that?

2023-12-08 17:04 UTC, kamil-tekiela commented
> Same changes would be applied in all apps with such code

Are you saying that there is some feature that would bring these spaces back?

I said I didn't change the behaviour when it comes to "function-like language constructs". I kept it as it was. It still removes spaces from `count()` or `empty()`, etc. You can even see this in the screenshot. My change only stops removing spaces from non-function-like constructs. 

This means that if someone has code like this:
```
echo ('Hello');
echo(' World');
```
The fixer will not make any changes to it. It will not add or remove spaces, because `echo` is not a function-like language construct. 

With my PR I expect no changes to existing user's code. Executing PHP-CS-fixer with this PR on existing code should create no diff. If it does, I did something wrong.

2023-12-08 17:14 UTC, Wirone commented
OK, that's a smaller BC-break, but still a break, because code that is fixed now (opinions aside, only current contract-wise), wouldn't be fixed anymore, which would lead to inconsistency in the codebase. Still think it should be behind the config option.

2023-12-14 21:56 UTC, Wirone commented
FYI: there's #6965 that is exactly about this case 🙂.

2024-03-28 12:09 UTC, closed without merging