fix: Do not mangle non-whitespace token in `PhpdocIndentFixer`
PHP-CS-Fixer/PHP-CS-Fixer pull request #8147
Opened 2024-07-30 14:57 UTC by blyxxyz

A colleague wrote this code:
```php
$foo->bar()/** @phpstan-ignore-next-line */
    ->baz();
```
`PhpdocIndentFixer` turns the `)` token into `)    `, causing a crash when another rule (in our case `NoSpacesAfterFunctionNameFixer`) can't find the closing parenthesis.

That output doesn't seem desirable to begin with but I've written a minimal fix to resolve only the crash.

2024-07-30 15:18 UTC, kubawerlos requested changes
Nice catch!

Since the changes are in only one fixer, please add to `PhpdocIndentFixerTest` test case with input code as input in `phpdoc_indent,no_spaces_after_function_name.test`.

2024-07-30 16:45 UTC, blyxxyz commented
Should I move the test case or duplicate it? There's no crash when running this rule in isolation so I don't think putting it in `PhpdocIndentFixerTest` would test it adequately?

2024-07-30 19:14 UTC, kubawerlos commented
Let's duplicate it.

> There's no crash when running this rule in isolation

That's true, but only after your changes.
On the main branch, it would crash for that input, no matter what an expected code would be.

2024-07-30 20:35 UTC, blyxxyz commented
Ah, I see now that the unit tests compare the tokens and not just the text. Makes sense, thanks.

2024-07-31 04:26 UTC, kubawerlos approved these changes

2024-07-31 04:26 UTC, merged

2024-07-31 04:27 UTC, kubawerlos commented
Thank you @blyxxyz