feat: add `PhpUnitDataProviderMethodOrderFixer` fixer
PHP-CS-Fixer/PHP-CS-Fixer pull request #8225
Opened 2024-09-29 15:22 UTC by mvorisek

close #7184

data provider tags are sorted by https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8220

2025-01-10 13:10 UTC, mvorisek commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +        $methodOrderFixer = new OrderedClassElementsFixer();
I want to be self critical here. The PR is done, but.

The current code using `OrderedClassElementsFixer` fixer here works perfectly to assert the expected order, but the diff is not ideal as other non-test/provider methods after/before might be moved too.

This can be verified when reverting #8302 and applying this fixer.

My plan here is to make the needed `OrderedClassElementsFixer` methods public temporary and then discuss refactoring to make the required methods public. This is needed in order to not copy code.

2025-01-26 13:42 UTC, mvorisek commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +        $methodOrderFixer = new OrderedClassElementsFixer();
Done!

2025-01-27 15:32 UTC, mvorisek commented
@keradus @kubawerlos can I have your review here?

2025-02-19 18:30 UTC, kubawerlos requested changes
Awesome tests, I wasn't able to come up with any new test cases. Just a few smacorrectionscts to do.

2025-02-19 18:30 UTC, kubawerlos commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +            'Data provider method must be placed after/before the first test where used.',
> the first test where used

If we use `after` option it will be moved after the last test where used - that is good, the description is to update.

2025-02-19 18:30 UTC, kubawerlos commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +        $endIndex = $elements[\count($elements) - 1]['end'];
```suggestion
        $endIndex = $elements[array_key_last($elements)]['end'];
```

2025-02-19 18:30 UTC, kubawerlos commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +            (new FixerOptionBuilder('placement', 'Prefix that replaces "test".'))
`PhpUnitDataProviderNameFixer` says hello 😄

2025-02-19 18:30 UTC, kubawerlos commented on tests/Fixer/Phpdoc/PhpdocOrderFixerTest.php
> +    /**
Are all method movements forgotten in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8302 or can they be reverted?

2025-02-19 23:01 UTC, mvorisek commented on src/Fixer/ClassNotation/OrderedClassElementsFixer.php
> +            $sorted = $this->sortElements($elements);
The code was only hard to read, the "ned index" is taken from unsorted elements.

2025-02-19 23:12 UTC, mvorisek commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +            'Data provider method must be placed after/before the first test where used.',
👍

2025-02-19 23:12 UTC, mvorisek commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +            (new FixerOptionBuilder('placement', 'Prefix that replaces "test".'))
👍 good catch!

2025-02-19 23:14 UTC, mvorisek commented on tests/Fixer/Phpdoc/PhpdocOrderFixerTest.php
> +    /**
I have removed this PR since then and improved it a lot.

2025-02-19 23:28 UTC, mvorisek commented on src/Fixer/PhpUnit/PhpUnitDataProviderMethodOrderFixer.php
> +        $endIndex = $elements[\count($elements) - 1]['end'];
👍 adjusted here and in `OrderedClassElementsFixer`

2025-02-20 18:03 UTC, kubawerlos approved these changes

2025-02-20 18:04 UTC, merged

2025-02-20 18:04 UTC, kubawerlos commented
Thank you @mvorisek