feat: Introduce `general_attribute_remove` fixer
PHP-CS-Fixer/PHP-CS-Fixer pull request #8339
Opened 2024-12-30 16:36 UTC by raffaelecarelle

fixes #7794

2025-01-05 00:34 UTC, keradus commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> + *  attributes?: list<string>
?
```suggestion
 *  attributes?: list<class-string>
```

2025-01-05 07:07 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> + *  attributes?: list<string>
Hello @keradus, I can't do that, because the command `composer cs:fix` fails reporting me the error:

![immagine](https://github.com/user-attachments/assets/28d116cf-779e-40a9-a957-ac9656d8514f)

2025-01-05 07:08 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> + *  attributes?: list<string>
so all workflow checks failed.

2025-01-05 14:25 UTC, keradus commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> + *  attributes?: list<string>
let's treat this outside of this PR scope then.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8347/commits/0aabb620b7352b0c41d355c8596d05b0b778d405

2025-01-05 14:27 UTC, keradus approved these changes
tbh, checking this PR was a pleasure. great job, @raffaelecarelle !

@kubawerlos @Wirone , any of you want to check it up ? if not, I will gladly merge as-is

2025-01-07 12:30 UTC, Wirone requested changes
Thanks @keradus for the mention, I took a look and have some feedback to address 🙂.

2025-01-07 12:30 UTC, Wirone commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
Personally I wouldn't follow `general_phpdoc_annotation_remove `'s "omitted" convention, as "omit" is like "skip", while the real intention here is to _remove_ the attribute(s). Also "should" does not fit here, as this is a _must_ when configured.

```suggestion
            'Removes configured attributes by their respective FQN.',
```

Or something like that.

2025-01-07 12:30 UTC, Wirone commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            foreach ($elements as $element) {
Remapping to `$elements` is superfluous, it does not bring any value. `AttributeAnalysis::getAttributes()` returns array of attributes' representation with `start`, `end` and `name`, so the remapping basically proxies all the data 1:1. All tests pass when I remove this and iterate over analysis' results:

```suggestion
            $endIndex = $attributeAnalysis->getEndIndex();

            $removedCount = 0;
            foreach ($attributeAnalysis->getAttributes() as $element) {
```

2025-01-07 12:30 UTC, Wirone commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            (new FixerOptionBuilder('attributes', 'List of attributes to remove FQ, e.g. `Foo\Bar`.'))
```suggestion
            (new FixerOptionBuilder('attributes', 'List of FQNs of attributes for removal.'))
```

the "e.g." part is not needed as examples are part of the docs.

2025-01-07 12:30 UTC, Wirone commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +    private function determineAttributeFullyQualifiedName(Tokens $tokens, string $name, int $index): string
This is basically copy-pasted from `OrderedAttributesFixer`, and it would be much better to extract it somewhere to reuse this logic instead of cloning it in another place.

<img width="1612" alt="image" src="https://github.com/user-attachments/assets/5af80e93-6841-46d4-9d85-4de6791d26b6" />

2025-01-07 12:30 UTC, Wirone commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +    private function collectNamespaceAnalysis(Tokens $tokens, int $startIndex): array
This is also a clone, it would be better to extract it, but maybe @keradus is OK with rule-level redundancy. It may be also done in separate PR, but it would be great to not forget about it.

2025-01-07 13:09 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
Hello @Wirone, thanks for your feedback. Fixed.

2025-01-07 13:09 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            foreach ($elements as $element) {
Good. Fixed.

2025-01-07 13:09 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            (new FixerOptionBuilder('attributes', 'List of attributes to remove FQ, e.g. `Foo\Bar`.'))
Fixed

2025-01-07 13:10 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +    private function determineAttributeFullyQualifiedName(Tokens $tokens, string $name, int $index): string
Yes, if you agree I can move this method under AttributeAnalyzer::class.

2025-01-07 13:11 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +    private function collectNamespaceAnalysis(Tokens $tokens, int $startIndex): array
Yes, if you agree I can move this method under AttributeAnalyzer::class. Or I can add a TODO for do it later in separated PR

2025-01-07 15:44 UTC, keradus commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
pls update for other `general*` fixer(s) in that case :D

2025-01-07 16:17 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +    private function collectNamespaceAnalysis(Tokens $tokens, int $startIndex): array
thanks @keradus, I moved the duplicated method under right scope (AttributeAnalyzer and NamespaceAnalyzer).

Then I fixed OrderedAttributesFixer and PhpUnitAttributesFixer to reflect the changes. Let me know

2025-01-07 16:19 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
sorry @keradus, I didn't get it what I should do

2025-01-07 22:16 UTC, keradus commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
could you apply Wirone's request to those files too?
```
src/Fixer/Phpdoc/GeneralPhpdocAnnotationRemoveFixer.php:            'Configured annotations should be omitted from PHPDoc.',
src/Fixer/Phpdoc/PhpdocNoAccessFixer.php:            '`@access` annotations should be omitted from PHPDoc.',
src/Fixer/Phpdoc/PhpdocNoEmptyReturnFixer.php:            '`@return void` and `@return null` annotations should be omitted from PHPDoc.',
src/Fixer/Phpdoc/PhpdocNoPackageFixer.php:            '`@package` and `@subpackage` annotations should be omitted from PHPDoc.',
```

2025-01-08 07:33 UTC, raffaelecarelle commented on src/Fixer/AttributeNotation/GeneralAttributeRemoveFixer.php
> +            'Configured attributes should be omitted (FQNs strings).',
ok, done.

2025-01-08 10:15 UTC, merged

2025-01-08 10:37 UTC, keradus commented
v3.67 you may find

2025-01-08 10:39 UTC, keradus commented
@Wirone , manual rebase or some automated by github?
if branch would simply get synced (git-merge, not git-rebase), it would work easier (no need to rewrite history of branch)

2025-01-08 11:28 UTC, Wirone commented
@keradus Rebase from the Github's UI. It does not matter since it's squashed when merged anyway, and it was only sync to enable merge, without actual changes. I just don't like merges 😅.